// <auto-generated />
using System;
using CGB_Habilitation.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace CGB_Habilitation.Migrations
{
    [DbContext(typeof(HabilitationDbContext))]
    [Migration("20251219085932_AddCodeAgent")]
    partial class AddCodeAgent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CGB_Habilitation.Models.Agence", b =>
                {
                    b.Property<Guid>("CodeAgence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("AdresseAgence")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NomAgence")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("CodeAgence");

                    b.ToTable("Agences");
                });

            modelBuilder.Entity("CGB_Habilitation.Models.Agent", b =>
                {
                    b.Property<Guid>("IdAgent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("CodeAgence")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("CodeAgent")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("CodeService")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime?>("DateLogin")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("EmailAgent")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("EstValide")
                        .HasColumnType("NUMBER(1)");

                    b.Property<Guid>("IdRole")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("LoginAgent")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NomAgent")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PasswordAgent")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PrenomAgent")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("SousCaisseAgent")
                        .HasColumnType("NUMBER(1)");

                    b.HasKey("IdAgent");

                    b.HasIndex("CodeAgence");

                    b.HasIndex("CodeService");

                    b.HasIndex("IdRole");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("CGB_Habilitation.Models.Habilitation", b =>
                {
                    b.Property<Guid>("IdHabilitation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<Guid>("CreerPar")
                        .HasColumnType("RAW(16)");

                    b.Property<DateTime>("DateCreationDemande")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Etat")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid>("IdAgent")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("Motif")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PieceJoint")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<Guid?>("TraiterPar")
                        .HasColumnType("RAW(16)");

                    b.Property<string>("TypeHabilitation")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdHabilitation");

                    b.HasIndex("IdAgent");

                    b.ToTable("Habilitations");
                });

            modelBuilder.Entity("CGB_Habilitation.Models.Role", b =>
                {
                    b.Property<Guid>("IdRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("NomRole")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("IdRole");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("CGB_Habilitation.Models.Service", b =>
                {
                    b.Property<Guid>("CodeService")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)");

                    b.Property<string>("NomService")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("TypeService")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("CodeService");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("CGB_Habilitation.Models.Agent", b =>
                {
                    b.HasOne("CGB_Habilitation.Models.Agence", "Agence")
                        .WithMany()
                        .HasForeignKey("CodeAgence")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGB_Habilitation.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("CodeService")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CGB_Habilitation.Models.Role", "RoleAgent")
                        .WithMany()
                        .HasForeignKey("IdRole")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agence");

                    b.Navigation("RoleAgent");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("CGB_Habilitation.Models.Habilitation", b =>
                {
                    b.HasOne("CGB_Habilitation.Models.Agent", "Agent")
                        .WithMany("Habilitations")
                        .HasForeignKey("IdAgent")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("CGB_Habilitation.Models.Agent", b =>
                {
                    b.Navigation("Habilitations");
                });
#pragma warning restore 612, 618
        }
    }
}
